name: Nextjs standalone CI/CD

on:
  push:
    branches: [main]

env:
  DOCKER_CONTAINER: next-ec2-docker-deploy-test-cicd
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/next-ec2-docker-deploy-test
  VERSION: ${{ github.sha }}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4

      - name: .next cache directory [Before Build]
        continue-on-error: true
        run: ls -la ${{ github.workspace }}/.next/cache

      # buildx(멀티 플랫폼 빌드 라이브러리, 개발 로컬 M1 -> EC2 리눅스 동일한 이미지 생성 플러그인)
      - name: SetUp Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 도커 레이어 캐싱
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.

      # .next > cache 캐싱
      - name: Exporting nextjs build cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: next-cache
          outputs: type=local,dest=.
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha

      - name: .next cache directory [After Build]
        continue-on-error: true
        run: ls -la ${{ github.workspace }}/.next/cache

  # runs-on : EC2 환경 (node v16, label-go)
  deploy:
    needs: build
    name: Deploy Job
    runs-on: [self-hosted, label-go]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker RUN
        run: |
          docker stop ${{ env.DOCKER_CONTAINER }} && docker rm ${{ env.DOCKER_CONTAINER }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 80:3000 --name ${{ env.DOCKER_CONTAINER }} --restart always ${{ env.DOCKER_IMAGE }}:latest
